MONGO_DB_NAME = "ctf"
MONGO_ADDR = "127.0.0.1"
MONGO_PORT = 27017
MONGO_USER = None
MONGO_PW = None

SECRET_KEY = "INSECURE_DEFAULT_CHANGE_ME"

SESSION_COOKIE_DOMAIN = None
SESSION_COOKIE_PATH = "/"
SESSION_COOKIE_NAME = "flask"

DOCKER_PUB = None
DOCKER_HOST = ""
DOCKER_CA = ""
DOCKER_CLIENT = ""
DOCKER_KEY = ""
DOCKER_CONTAINERS_PER_TEAM = 5
