---
# Defaults for the picoCTF-web role. These are the lowest priority variables
# and can easily be overridden in group_vars, host_vars, or the command line.

# pico_base_dir set in common.yml
shell_manager_dir:  "{{pico_base_dir}}/picoCTF-shell"

###
# wetty configuration
###
wetty_js_path: "/opt/hacksports/wetty/node_modules/wetty.js"

# configure nginx
shell_site_config_name: "shell"
wetty_port: "4242"
wetty_server_path: "http://127.0.0.1:{{ wetty_port }}/"

# problem settings
deb_dir:    "/picoCTF-debs"
bundle_dir: "/picoCTF-bundles"

##
# Problem Settings
# These will only be used if `problem_source_dirs` and `bundles` are not
# specified in an environmental configuration AND `auto_load_problems` is True
##
problem_source_dirs:
  - "{{ pico_base_dir }}/problems/examples"

bundles:
  - {
    source: "{{ pico_base_dir }}/problems/bundles/challenge-sampler.json",
    name: "challenge-sampler",
    instances: 2
  }
