---
# Playbook that installs the dependencies for the picoCTF-web server

- name: Update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600

# Extracted from picoCTF-platform/scripts/web_setup.sh
- name: Install picoCTF platform system dependencies
  apt:
    name: [
        'gunicorn',
        'jekyll',
        'libffi-dev',
        'libssl-dev',
        'nginx',
        'python-virtualenv',
        'python3-pip',
        'python3.7-dev',
        'python3.7-venv',
        'python3.7',
        ]
    state: present

- name: Install pymongo in (new) virtualenv
  pip:
    name: pymongo
    virtualenv: "{{ virtualenv_dir }}"
    virtualenv_python: python3.7

- name: Install python packaging
  pip:
    name: packaging
    virtualenv: "{{ virtualenv_dir }}"

- name: Install python appdirs
  pip:
    name: appdirs
    virtualenv: "{{ virtualenv_dir }}"
