---
# Playbook that installs MongoDB and associated utilities
# TODO: Consolidate mongodb tasks into web

- name: Add apt key by id
  apt_key:
    keyserver: "{{mongodb_apt_keyserver}}"
    id: "{{mongodb_apt_key_id}}"

- name: Add repository
  apt_repository:
    repo: "{{ mongodb_repo }}"
    state: present

- name: Update apt
  apt:
    update_cache: yes

- name: Install mongo and python packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python3.6       # from PPA
    - python3.6-dev
    - python3.6-venv
    - python-virtualenv
    - python-pip
    - mongodb-org     # from PPA

- name: Install pymongo in (new) virtualenv
  pip:
    name: pymongo
    virtualenv: "{{ virtualenv_dir }}"
    virtualenv_python: python3.6

- name: Ensure mongodb is running
  service:
    name: "{{ mongodb_daemon_name }}"
    state: started
    enabled: yes
