---
# Playbook that installs the dependencies for the picoCTF-shell server

- name: Update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600

# Add repositories for NodeJS and yarn
- name: Add nodeJS and yarn repository/keys
  shell: |
    curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  args:
    warn: False

# Extracted from picoCTF-platform/scripts/shell_setup.sh
- name: Install picoCTF-shell system dependencies
  apt:
    state: present
    name: [
      'dpkg-dev',
      'dpkg',
      'fakeroot',
      'gcc-multilib',
      'libffi-dev',
      'libssl-dev',
      'nginx',
      'nodejs',
      'php7.2-cli',       # php5 package deprecated
      'php7.2-sqlite3',   # used to serve shellinabox and challenge binaries
      'python-pip',       # used for pam module dependencies
      'python-virtualenv',
      'python3-pip',      # used for shell_manager dependencies
      'python3.7-dev',
      'python3.7-venv',
      'python3.7',        # from PPA, to cover all likely interpreter directives
      'python3',          # used by shell_manager
      'shellinabox',
      'socat',
      'software-properties-common',
      'xinetd',
      ]

# Needed by templated challenge types
- name: Install uwsgi and plugins for shell server
  apt:
    name: [
        'python-flask',
        'uwsgi-plugin-php',
        'uwsgi-plugin-python',
        'uwsgi-plugin-python3',
        'uwsgi',
        ]
    state: present

- name: Install pam dependencies
  apt:
    name: [
        'libpam-python',
        'python-setuptools',
        ]
    state: present

# System python packages updates needed for pam_auth module and Ansible
- name: Update pyOpenSSL
  pip:
    name: pyOpenSSL
    version: 18.0.0

- name: Update cryptography
  pip:
    name: cryptography
    version: 2.2.2

- name: Install requests
  pip:
    name: requests
    version: 2.19.1

- name: Install python packaging in (new) virtualenv
  pip:
    name: packaging
    virtualenv: "{{ virtualenv_dir }}"
    virtualenv_python: python3.7

- name: Install python appdirs
  pip:
    name: appdirs
    virtualenv: "{{ virtualenv_dir }}"

# Fix https://github.com/picoCTF/picoCTF/issues/150
- name: Replace /bin/sh with wrapper script to preserve privilege
  copy:
    content: |
      #!/bin/dash -p
      exec /bin/dash -p "$@"
    dest: /bin/sh
    owner: root
    group: root
    mode: 0755

- name: Install common apt packages for CTF shell servers
  apt:
    state: present
    name: [
      # archive tools
      'bzip2',
      'gzip',
      'tar',
      'unzip',
      'zip',
      # build tools
      'build-essential',
      'gdb',
      'nasm',
      'perl',
      'python',
      'python3',
      'ruby',
      # common command line tools
      'dos2unix',
      'gawk',
      'grep',
      'jq',
      'sed',
      'silversearcher-ag',
      # editors
      'bvi',
      'emacs-nox',
      'joe',
      'nano',
      'tweak',
      'vim-nox',
      # forensics tools
      'foremost',
      'scalpel',
      'sleuthkit',
      'testdisk',
      'tshark',
      # networking tools
      'curl',
      'netcat-openbsd',
      'socat',
      'traceroute',
      'wget',
      # terminal multiplexers
      'screen',
      'tmux',
      # z: misc
      'expect',
      'pandoc', # for `pip install pwntools`
      ]

- name: Ensure nano is the default editor
  alternatives:
    name: editor
    path: /bin/nano

- name: Install common pip2 packages for CTF shell servers
  pip:    # ipython 6.0 dropped support for Python2
    name: [
        'ipython<6.0',
        'ptpython',
        'pwntools',
        ]

- name: Install common pip3 packages for CTF shell servers
  pip:
    name: [
        'ipython',
        'ptpython',
        'pwntools',
        ]
    executable: pip3
  when: False # pwntools is not ready for python3; skipping to avoid confusion
