---
# Playbook that installs the dependencies for the picoctf-shell server

- name: Update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600

# Extracted from picoCTF-platform/scripts/shell_setup.sh
- name: Install picoCTF-shell system dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - software-properties-common
    - xinetd
    - dpkg
    - dpkg-dev
    - fakeroot
    - python-virtualenv
    - python-pip      # used for pam module dependencies
    - python3         # used by shell_manager
    - python3-pip     # used for shell_manager dependencies
    - python3.6       # from PPA, to cover all likely interpreter directives
    - python3.6-dev
    - python3.6-venv
    - libffi-dev
    - libssl-dev
    - socat
    - php7.0-cli      # php5 package deprecated
    - php7.0-sqlite3
    - gcc-multilib
    - nginx           # used to serve shellinabox and challenge binaries
    - shellinabox


# Needed by templated challenge types
- name: Install uwsgi and plugins for shell server
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - uwsgi
    - uwsgi-plugin-php
    - uwsgi-plugin-python3
    - uwsgi-plugin-python
    - python-flask

- name: Install pam dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - libpam-python
    - python-setuptools

# System python packages updates needed for pam_auth module and Ansible
- name: Update pyOpenSSL
  pip:
    name: pyOpenSSL
    version: 18.0.0

- name: Update cryptography
  pip:
    name: cryptography
    version: 2.2.2

- name: Install requests
  pip:
    name: requests
    version: 2.19.1

- name: Install python packaging in (new) virtualenv
  pip:
    name: packaging
    virtualenv: "{{ virtualenv_dir }}"
    virtualenv_python: python3.6

- name: Install python appdirs
  pip:
    name: appdirs
    virtualenv: "{{ virtualenv_dir }}"
