
key_dir: "/etc/docker/keys"

socket_host: "-H unix:///var/run/docker.sock"
tcp_host: "-H=0.0.0.0:2376"

# Certificate Authority files
ca_key : "{{key_dir}}/ca-key.pem"
ca_crt : "{{key_dir}}/ca.pem"
ca_csr : "{{key_dir}}/ca.csr"

# Docker Server files
srv_key: "{{key_dir}}/server-key.pem"
srv_csr: "{{key_dir}}/server.csr"
srv_crt: "{{key_dir}}/server.pem"
server_CN: "docker.local"
server_SAN: []

client: local
user: "{{ansible_user}}"
